name = "link-redirect"
main = "link-redirect.js"
compatibility_date = "2026-07-19"

# Route the Worker to the subdomain
routes = [
  { pattern = "notion.techfusionreport.com/*", zone_name = "techfusionreport.com" }
]

# KV namespace binding for slug -> destination URL lookups.
kv_namespaces = [
  { binding = "LINKS", id = "1359ef24efa64810b23651a001542be5" }
]
